spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true
  # AWS 애플리케이션 실행 시 일래스틱 빈스토크에서 값을 덮어쓰므로 삭제
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}
            client-secret: ${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}
            scope:
              - email
              - profile
  jwt:
    issuer: ${{ secrets.JWT_ISSUER }}
    secret_key: ${{ secrets.JWT_SECRET_KEY }}